### ISSUE TITLE
Error:  redirection forbidden

### ISSUE THREAD

**Issue by Akronix** [hackercouch/hackercouch#170] opened 2018-12-31 18:35 UTC
I'm trying to add my couch and I'm getting this error when run locally:
```
> $ bundle exec jekyll serve --watch --trace                                                                                                       ⬡ 10.14.1 [±akronix ●]
Configuration file: /home/akronix/workspace/hackercouch/_config.yml
            Source: /home/akronix/workspace/hackercouch
       Destination: /home/akronix/workspace/hackercouch/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://nominatim.openstreetmap.org/search/TUR/istanbul?format=json -> https://nominatim.openstreetmap.org/search/TUR/istanbul?format=json (RuntimeError)
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/open-uri-cached-0.0.5/lib/open-uri/cached.rb:10:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /home/akronix/workspace/hackercouch/_plugins/to_geojson.rb:21:in `block in generate'
	from /home/akronix/workspace/hackercouch/_plugins/to_geojson.rb:16:in `each'
	from /home/akronix/workspace/hackercouch/_plugins/to_geojson.rb:16:in `generate'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:175:in `block in generate'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:173:in `each'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:173:in `generate'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:70:in `process'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:93:in `each'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:93:in `start'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/bin/jekyll:23:in `load'
	from /home/akronix/workspace/hackercouch/vendor/bundle/ruby/2.3.0/bin/jekyll:23:in `<main>'
```

**Comment by captn3m0** [comment] 2019-01-01 20:43
I tested this locally, and was not able to reproduce so far. 

I tried against your committed file as well: https://github.com/Akronix/hackercouch/commit/285a2b7cc487fef17746a3eda3836b04a10287fa

The only change I'd suggest is to replace

`country: Spain` with `country: ES`, since we use the ISO codes, but I was able to run this even without the change.

(tested on ruby 2.5, though it should not make a difference)

**Comment by captn3m0** [comment] 2019-01-19 04:36
Try clearing your `_cache` directory and hopefully that should fix it.

**Comment by Akronix** [comment] 2019-01-19 16:37
It didn't I'm afraid...

**Comment by captn3m0** [comment] 2019-01-19 19:41
Can you file the PR with your couch for now, and I'll make sure it gets merged.

**Comment by Akronix** [comment] 2019-01-19 22:01
I added my couch in https://github.com/hackercouch/hackercouch/pull/173

**Comment by captn3m0** [comment] 2019-10-01 10:13
Stale report, so closing. Likely fixed with ruby/jekyll upgrades since.

**Closed as completed by captn3m0** 2019-10-01 10:13 UTC
Labels: bug
